import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Instagram",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/svgs/instagram-1.svg" />
        <meta name="theme-color" content="#000000" />
      </head>
      <body className={inter.className}>
        <p className=" fixed top-0 flex justify-center w-full bg-black text-white z-20">
          <b className="animate-pulse">Basic clone front-end</b>
        </p>
        {children}
      </body>
    </html>
  );
}
